### ISSUE TITLE
environment for pip install

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-ml-docs#2]
@johngian So the current project in the [documentation](https://webcompat-ml.readthedocs.io/en/latest/installation.html) recommends to do.

```
$ pip install .
```

but this will install globally the modules… which is not really cool. 
and i unfortunately realized that… too late.

**Comment by johngian** [comment]
I think its pretty common for python packages to suggest installing the packages by `pip install` and let users figure out if the path is global, user, or virtualenv. I can add a comment there to suggest using virtualenv. Do you think that's enough?

**Comment by karlcow** [comment]
This would be good indeed.

```
$ git clone https://github.com/mozilla/webcompat-ml
$ cd webcompat-ml
$ python -m venv env
$ . env/bin/activate
$ pip install .
```

But anyway it doesn't work
https://github.com/mozilla/webcompat-ml/issues/9

so there are bigger issues.

**Comment by karlcow** [comment]
IT would be cool to understand how you work with the project, because right now it's opaque. I'm pretty sure it's super logical for you. But for me I have been struggling with the 4 repos and how all of this is both coded and deployed.  🤣
